namespace VastDark.Domain;

public enum RuinTreasureMagnitude { Useful, Special, GreatAndTerrible }
public sealed record RuinTreasureRule(int Roll, RuinTreasureMagnitude Magnitude, string Name, string Effect);

/// <summary>Page 31 depth-adjusted treasure categories and their persistent effects.</summary>
public static class RuinTreasureRules
{
    private static readonly IReadOnlyDictionary<RuinTreasureMagnitude, IReadOnlyList<RuinTreasureRule>> Treasures = new Dictionary<RuinTreasureMagnitude, IReadOnlyList<RuinTreasureRule>>
    {
        [RuinTreasureMagnitude.Useful] = [
            new(1,RuinTreasureMagnitude.Useful,"Seer Stone","Navigate when landmarks are invisible."),new(2,RuinTreasureMagnitude.Useful,"Spell Eater","Once daily absorb one spell targeting you."),new(3,RuinTreasureMagnitude.Useful,"Dowsing Charm","Points to nearest water."),new(4,RuinTreasureMagnitude.Useful,"Bleeder","Blade wounds deal 1d6 each day."),new(5,RuinTreasureMagnitude.Useful,"Torch Stone","Feed 1 HP for one hour lantern light."),new(6,RuinTreasureMagnitude.Useful,"Alarm Band","Vibrates near Crawl."),new(7,RuinTreasureMagnitude.Useful,"Hearth Charm","Cold resistance and lights kindling."),new(8,RuinTreasureMagnitude.Useful,"Grim Spirits","Advantage against fear, charm, psychological effects."),new(9,RuinTreasureMagnitude.Useful,"Grindsaw","Cuts rock and metal."),new(10,RuinTreasureMagnitude.Useful,"Grenado","Thrown: 2d6 piercing/fire within 30 ft."),new(11,RuinTreasureMagnitude.Useful,"Crimson Salt","Ignore chosen ability exhaustion for 24 hours."),new(12,RuinTreasureMagnitude.Useful,"Foul Lure","Attracts Crawl when opened.")],
        [RuinTreasureMagnitude.Special] = [
            new(1,RuinTreasureMagnitude.Special,"Dreamless","No sleep needed; appearance grows haggard."),new(2,RuinTreasureMagnitude.Special,"Stone Dance","Coated item passes through stone."),new(3,RuinTreasureMagnitude.Special,"Weigh No More","Held wielder is weightless."),new(4,RuinTreasureMagnitude.Special,"Unmoved","Struck cube stays immovable until verbally released."),new(5,RuinTreasureMagnitude.Special,"Lying Coin","Hums when lies are told."),new(6,RuinTreasureMagnitude.Special,"Melder","Fresh dead heals 1d6 HP/minute while absorbed."),new(7,RuinTreasureMagnitude.Special,"Whispering Glass","Mouth-held telepathy within 30 ft."),new(8,RuinTreasureMagnitude.Special,"Twisted Sliver","Contort body to 6-inch diameter."),new(9,RuinTreasureMagnitude.Special,"Empty Gasp","No breathing needed; painful whisper voice."),new(10,RuinTreasureMagnitude.Special,"Shivers","Freezes touched liquids, one gallon/hour."),new(11,RuinTreasureMagnitude.Special,"Sever","Detach/control limbs; reattach within one hour or die."),new(12,RuinTreasureMagnitude.Special,"Sunder","Thrown block collapses room/building after 1d3 minutes.")],
        [RuinTreasureMagnitude.GreatAndTerrible] = [
            new(1,RuinTreasureMagnitude.GreatAndTerrible,"Transference","Bring back dead by sacrificing another life."),new(2,RuinTreasureMagnitude.GreatAndTerrible,"Forgotten","Written thoughts spread forgetting."),new(3,RuinTreasureMagnitude.GreatAndTerrible,"Annihilation","Staff-killed victims are removed from memory."),new(4,RuinTreasureMagnitude.GreatAndTerrible,"Incineration","Colorless flame cannot be extinguished."),new(5,RuinTreasureMagnitude.GreatAndTerrible,"Transmutation","Touched things turn to lead."),new(6,RuinTreasureMagnitude.GreatAndTerrible,"Command","Hearers obey commands."),new(7,RuinTreasureMagnitude.GreatAndTerrible,"Lament","Steal a memory and transfer it to yourself."),new(8,RuinTreasureMagnitude.GreatAndTerrible,"Observance","Replace eyes to see through aware persons."),new(9,RuinTreasureMagnitude.GreatAndTerrible,"Power","Permanent Grit 0/Flesh 1; cast without material or sacrifice."),new(10,RuinTreasureMagnitude.GreatAndTerrible,"Commune","Wish granted; wielder disappears.")],
    };
    public static RuinTreasureMagnitude GetMagnitude(int d20PlusDepth) => d20PlusDepth switch { <= 0 => throw new ArgumentOutOfRangeException(nameof(d20PlusDepth)), <= 10 => RuinTreasureMagnitude.Useful, <= 19 => RuinTreasureMagnitude.Special, _ => RuinTreasureMagnitude.GreatAndTerrible };
    public static RuinTreasureRule Get(RuinTreasureMagnitude magnitude, int roll) => Treasures[magnitude].SingleOrDefault(treasure => treasure.Roll == roll) ?? throw new ArgumentOutOfRangeException(nameof(roll));
}
