namespace VastDark.Domain;

public sealed record RuinRoomEffectRule(int Code, string RoomName, string Procedure, string? Save = null, string? Damage = null);

/// <summary>All printed pages 22-27 room procedures. Duplicate code 45 is preserved as Reliquary and Fountain.</summary>
public static class RuinRoomEffectRules
{
    private static readonly IReadOnlyList<RuinRoomEffectRule> Rules =
    [
        new(11,"Plaza","Statue Garden: 2-in-6 Bandit ambushers; Obelisk: 2d10 coins + 1d6 tools; or eerily empty."), new(12,"Graveyard","Hollow Coffers: sledge opens silver coin coffers and rolls encounter; or Charnel House/Quiet."), new(13,"Archive","Carved shelves are climbable; Teetering shelves can domino for 10d6 and roll encounter.",Damage:"10d6"), new(14,"Kennel","Roll d6: nothing, tool, terrified Traveler, or Crawl."), new(15,"Oubliette","Breath save crossing or fall 1d6×10 feet; pit has corpse pile tools, treasure, or trapped companion.","Breath","1d6×10 fall"), new(16,"Temple","Altar: 1d6×50 coin metal; Throne: Treasure; Worshipers: 1d20 Bandit-stat attackers if disturbed."),
        new(21,"Pit","Tiered/Distressed: Depth +1; Shear requires climbing gear and adds 1d6 Depth."), new(22,"Vault","Break thick iron door for 1d10×100 lodestone coins and 1d3 treasures."), new(23,"Atrium","1d6 Traveler camp trades goods and information."), new(24,"Tower","At Depth >1 leads surface; 2-in-6 stairs otherwise climb."), new(25,"Ossuary","Search hole d6: bone, oil, coin, lodestone, 1d6 bite, or keepsake.",Damage:"1d6"), new(26,"Great Hall","Noise travels; roll encounter twice."),
        new(31,"Maze","Require three consecutive Intelligence successes; failure loses 1d6 hours and rolls encounter."), new(33,"Bathhouse","Water replenishes daily, drink only distilled/sanitized; 1-in-20 treasure."), new(34,"Amphitheater","False whispers, 2d6 hostile-on-disturbance observers, or Thespian lore interaction."), new(35,"Cellar","Cold storage prevents rot, decay, and aging."), new(36,"Planetarium","Meditation/dream uses 1d20+WIS/INT/CHA: memory loss, exhaustion, advantage, next rooms, memory recovery, or Wyrm/treasure."),
        new(41,"Dormitory","Resting creates unbreakable stasis sleep until awakened; 1-in-6 sleeper."), new(42,"Dump","Each search hour: 3-in-6 find tool/1d6×10 lodestone/1d3 rations and 3-in-6 suffer 1d6 damage, exhaustion, or encounter.",Damage:"1d6"), new(43,"Pyramid","Capstone 500lb worth 1d6×200; hum requires hourly Charm save/exhaustion; disturbance landslide 5d6.","Charm","5d6"), new(44,"Nave","Each meditation hour 3-in-6 gains next rooms/1d3 Grit/spell and 3-in-6 loses spell, gains exhaustion, or encounter."), new(45,"Reliquary","Crawl Effigy yields 1d6 materials; Oracle Skull daily question; Magus Bones daily random spell or consume to learn chosen spell."), new(45,"Fountain","Drain receives constant frigid water, steaming blood, or fine dust."), new(46,"Colonnade","Roll encounters twice."),
        new(51,"Canyon","Bridge one at a time/10 minutes; hidden path needs climbing; fish 1d6 hours for 1d3 rations with 1-in-6 Crawl; descend +1d10 Depth."), new(52,"Kiln","Fires persist until intentionally snuffed."), new(53,"Well","Hook/trawl 1-in-6 for useless, dead, tool, 1d6 rations, treasure, or encounter."), new(54,"Corridor","Squeeze single-file; Hollow loud noise rolls encounter; Twisted travel exits random direction."), new(55,"Mosaic","Copies count as Wastes maps; each harvest hour gains 1d10×10 lodestone and rolls encounter."), new(56,"Garden","2d6 Delvers attack anyone harming sculptures."),
        new(61,"Scriptorium","Magic save or hypnotized/catatonic; strong blow ends it; 1-in-6 transfixed Delver with no prior memory.","Magic"), new(62,"Oasis","No encounters or harm while sitting by pool."), new(63,"Quarry","Breath save or 5d6 damage crossing; tools/climbing gear negate.","Breath","5d6"), new(64,"Coliseum","All attacks maximum damage; slain monsters/assailants heal slayer 1d6 Grit per HD."), new(65,"Lighthouse","Leave personal effect and whisper memory; next sleep returns here missing items."), new(66,"Observatory","Study pipe sounds to predict next 1d6 encounters."),
    ];
    public static IReadOnlyList<RuinRoomEffectRule> Get(int code, string roomName) => Rules.Where(rule => rule.Code == code && string.Equals(rule.RoomName, roomName, StringComparison.OrdinalIgnoreCase)).ToList();
    public static IReadOnlyList<RuinRoomEffectRule> All => Rules;
}
